"""Public provider-neutral LLM service contracts."""

from .provider_transport import (
    LLMProviderRequestError,
    ProviderCallResult,
    ProviderRateGate,
    ProviderRateLimitSnapshot,
    ProviderResponseMetadata,
    ProviderRetrySettings,
    ProviderTransportAttempt,
)
from .structured_output import (
    StructuredOutputCapabilities,
    StructuredOutputMode,
    StructuredOutputPolicy,
    prepare_structured_output,
    resolve_structured_output_capabilities,
)
from .tool_calling import (
    LLMToolCallCapabilityError,
    LLMToolCallError,
    LLMToolCallProviderRequestError,
    LLMToolCallResponseError,
    ToolCall,
    ToolCallRequest,
    ToolCallResponse,
    ToolDefinition,
)
from .types import (
    LLMContextWindowExceededError,
    LLMRequestEstimate,
    LLMRunQuotaError,
    LLMRunQuotaExceededError,
    LLMRunQuotaWouldExceedError,
    LLMStructuredOutputCapabilityError,
    LLMStructuredOutputError,
    LLMStructuredOutputParseError,
    LLMStructuredOutputProviderRequestError,
    LLMStructuredOutputRefusalError,
    LLMStructuredOutputTruncationError,
    LLMStructuredOutputValidationError,
    PromptCacheRequest,
    StructuredOutputRequest,
)

__all__ = [
    "LLMContextWindowExceededError",
    "LLMProviderRequestError",
    "LLMRequestEstimate",
    "LLMRunQuotaError",
    "LLMRunQuotaExceededError",
    "LLMRunQuotaWouldExceedError",
    "LLMStructuredOutputCapabilityError",
    "LLMStructuredOutputError",
    "LLMStructuredOutputParseError",
    "LLMStructuredOutputProviderRequestError",
    "LLMStructuredOutputRefusalError",
    "LLMStructuredOutputTruncationError",
    "LLMStructuredOutputValidationError",
    "LLMToolCallCapabilityError",
    "LLMToolCallError",
    "LLMToolCallProviderRequestError",
    "LLMToolCallResponseError",
    "PromptCacheRequest",
    "ProviderCallResult",
    "ProviderRateGate",
    "ProviderRateLimitSnapshot",
    "ProviderResponseMetadata",
    "ProviderRetrySettings",
    "ProviderTransportAttempt",
    "StructuredOutputCapabilities",
    "StructuredOutputMode",
    "StructuredOutputPolicy",
    "StructuredOutputRequest",
    "ToolCall",
    "ToolCallRequest",
    "ToolCallResponse",
    "ToolDefinition",
    "prepare_structured_output",
    "resolve_structured_output_capabilities",
]
