"""Canonical contracts for selecting and opening AG storage providers."""

from .capabilities import StorageCapabilities, StorageCapability
from .errors import (
    DuplicateStorageProviderError,
    StorageCapabilityError,
    StorageConfigurationError,
    StorageConflictError,
    StorageError,
    StorageFormatError,
    StorageHealthError,
    StorageIntegrityError,
    StorageNotFoundError,
    StorageProviderRegistrationError,
    StorageReadOnlyError,
    StorageScopeError,
    StorageTimeoutError,
    UnknownStorageProviderError,
)
from .pagination import MAX_STORAGE_PAGE_SIZE, Page, PageRequest
from .provider import (
    StorageBundle,
    StorageClock,
    StorageHealth,
    StorageOpenMode,
    StorageOpenRequest,
    StorageProvider,
    StorageProviderSelection,
    StorageSecretResolver,
)
from .records import (
    ArtifactAction,
    ArtifactOccurrence,
    ArtifactRecord,
    ArtifactRelation,
    ArtifactRelationKind,
    BlobHead,
    BlobRange,
    BlobWriteResult,
    EventDraft,
    EventRecord,
    FrozenJson,
    SearchDocument,
    SearchMode,
    SearchQuery,
    SearchResult,
    StateRecord,
)
from .scope import StorageScope
from .stores import (
    ArtifactRepository,
    BlobStore,
    EventQuery,
    EventStore,
    SearchBackend,
    SortDirection,
    StateHistoryQuery,
    StateStore,
)
from .supporting import (
    DocumentQuery,
    DocumentRecord,
    DocumentStore,
    KeyValueQuery,
    KeyValueRecord,
    KeyValueStore,
)

__all__ = [
    "DuplicateStorageProviderError",
    "ArtifactAction",
    "ArtifactOccurrence",
    "ArtifactRecord",
    "ArtifactRelation",
    "ArtifactRelationKind",
    "ArtifactRepository",
    "BlobHead",
    "BlobRange",
    "BlobStore",
    "BlobWriteResult",
    "EventDraft",
    "EventRecord",
    "EventQuery",
    "EventStore",
    "FrozenJson",
    "DocumentQuery",
    "DocumentRecord",
    "DocumentStore",
    "MAX_STORAGE_PAGE_SIZE",
    "Page",
    "PageRequest",
    "KeyValueQuery",
    "KeyValueRecord",
    "KeyValueStore",
    "SearchDocument",
    "SearchBackend",
    "SearchMode",
    "SearchQuery",
    "SearchResult",
    "StateRecord",
    "SortDirection",
    "StateHistoryQuery",
    "StateStore",
    "StorageBundle",
    "StorageCapabilities",
    "StorageCapability",
    "StorageCapabilityError",
    "StorageClock",
    "StorageConfigurationError",
    "StorageConflictError",
    "StorageError",
    "StorageFormatError",
    "StorageHealth",
    "StorageHealthError",
    "StorageIntegrityError",
    "StorageNotFoundError",
    "StorageOpenMode",
    "StorageOpenRequest",
    "StorageProvider",
    "StorageProviderRegistrationError",
    "StorageProviderSelection",
    "StorageReadOnlyError",
    "StorageScope",
    "StorageScopeError",
    "StorageTimeoutError",
    "StorageSecretResolver",
    "UnknownStorageProviderError",
]
