"""Canonical contracts for selecting and opening AG storage providers."""

from .capabilities import StorageCapabilities, StorageCapability
from .errors import (
    DuplicateStorageProviderError,
    StorageCapabilityError,
    StorageConfigurationError,
    StorageConflictError,
    StorageError,
    StorageFormatError,
    StorageHealthError,
    StorageProviderRegistrationError,
    StorageReadOnlyError,
    StorageScopeError,
    UnknownStorageProviderError,
)
from .pagination import MAX_STORAGE_PAGE_SIZE, Page, PageRequest
from .provider import (
    StorageBundle,
    StorageClock,
    StorageHealth,
    StorageOpenMode,
    StorageOpenRequest,
    StorageProvider,
    StorageProviderSelection,
    StorageSecretResolver,
)
from .records import (
    ArtifactAction,
    ArtifactOccurrence,
    ArtifactRecord,
    ArtifactRelation,
    ArtifactRelationKind,
    EventDraft,
    EventRecord,
    FrozenJson,
    SearchDocument,
    SearchMode,
    SearchQuery,
    SearchResult,
    StateRecord,
)
from .scope import StorageScope

__all__ = [
    "DuplicateStorageProviderError",
    "ArtifactAction",
    "ArtifactOccurrence",
    "ArtifactRecord",
    "ArtifactRelation",
    "ArtifactRelationKind",
    "EventDraft",
    "EventRecord",
    "FrozenJson",
    "MAX_STORAGE_PAGE_SIZE",
    "Page",
    "PageRequest",
    "SearchDocument",
    "SearchMode",
    "SearchQuery",
    "SearchResult",
    "StateRecord",
    "StorageBundle",
    "StorageCapabilities",
    "StorageCapability",
    "StorageCapabilityError",
    "StorageClock",
    "StorageConfigurationError",
    "StorageConflictError",
    "StorageError",
    "StorageFormatError",
    "StorageHealth",
    "StorageHealthError",
    "StorageOpenMode",
    "StorageOpenRequest",
    "StorageProvider",
    "StorageProviderRegistrationError",
    "StorageProviderSelection",
    "StorageReadOnlyError",
    "StorageScope",
    "StorageScopeError",
    "StorageSecretResolver",
    "UnknownStorageProviderError",
]
