from __future__ import annotations

import hashlib
import json
import re
import sys
import types
from typing import Any

from aethergraph.core.runtime.node_context import NodeContext
from aethergraph.plugins.agents.graph_builder.types import GRAPH_BUILDER_SKILL_ID, _load_state

_GRAPHIFY_DECORATOR_RE = re.compile(r"@graphify\s*\((?P<args>[^)]*)\)", flags=re.DOTALL)
_GRAPHFN_DECORATOR_RE = re.compile(r"@graph_fn\s*\((?P<args>[^)]*)\)", flags=re.DOTALL)


def _extract_graph_name_from_decorator_args(args: str) -> str | None:
    """
    Very simple parser to pull out name="..." from decorator kwargs.
    """
    m = re.search(r"name\s*=\s*['\"]([^'\"]+)['\"]", args)
    if m:
        return m.group(1).strip()
    return None


def _discover_graph_name_from_source(code: str) -> str | None:
    """
    Look for @graphify(...) or @graph_fn(...), try to recover the graph name.
    Fallback: the def name right after the decorator.
    """
    text = code or ""

    for dec_re in (_GRAPHIFY_DECORATOR_RE, _GRAPHFN_DECORATOR_RE):
        m = dec_re.search(text)
        if m:
            args = m.group("args")
            name = _extract_graph_name_from_decorator_args(args)
            if name:
                return name
            # fallback: next def after decorator
            suffix = text[m.end() :]
            m_def = re.search(r"def\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(", suffix)
            if m_def:
                return m_def.group(1).strip()

    return None


async def _resolve_registration_target(
    *,
    context: NodeContext,
    files: list[Any] | None,
) -> tuple[str | None, str | None]:
    """
    Decide which graph to register and (optionally) its source code.

    Returns: (graph_name, code_text) or (None, None) if nothing obvious.

    Priority:
      1) Any BuilderFileRef in `files` that looks like it defines a graph
         (preferring kind="code", then "notebook", and preferring source="artifact").
      2) Last generated code stored in GraphBuilderState.
    """
    files = files or []

    artifacts = context.artifacts()
    state = await _load_state(context=context, level="user")

    # 1) Prioritize code-like BuilderFileRef entries
    prioritized: list[tuple[int, Any, str]] = []

    for f in files:
        # Expecting BuilderFileRef-like attributes:
        #   name: str | None
        #   mimetype: str | None
        #   source: Literal["upload", "artifact"]
        #   artifact_id: str | None
        #   uri: str | None
        #   kind: Literal["code", "notebook", "text", "other"]
        uri = getattr(f, "uri", None)
        artifact_id = getattr(f, "artifact_id", None)
        if not uri and not artifact_id:
            continue

        kind = getattr(f, "kind", None)
        source = getattr(f, "source", None)

        score = 0
        if kind == "code":
            score += 10
        elif kind == "notebook":
            score += 5
        if source == "artifact":
            score += 2

        prioritized.append((score, f, uri))

    # Highest score first
    prioritized.sort(key=lambda t: t[0], reverse=True)

    for _score, f, uri in prioritized:  # noqa: B007
        try:
            if uri:
                text = await artifacts.load_text(uri=uri)
            else:
                text = await artifacts.load_text_by_id(f.artifact_id)
        except Exception:
            # skip non-text or invalid references
            continue

        graph_name = _discover_graph_name_from_source(text)
        if graph_name:
            return graph_name, text

    # 2) Fallback to last generated code in state
    if state.last_graph_name and state.last_generated_code:
        return state.last_graph_name, state.last_generated_code

    return None, None


def _fallback_app_config(
    *,
    graph_name: str,
    plan: dict[str, Any] | None,
    input_schema: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """
    Very defensive fallback if the LLM fails to produce JSON.
    """
    graph = (plan or {}).get("graph") or {}
    inputs = graph.get("inputs") or []
    short = graph.get("description") or f"App for {graph_name}"
    desc = graph.get("long_description") or (
        "App generated by Graph Builder from a workflow plan. "
        "Runs the graph and produces outputs defined by the workflow."
    )

    # crude mode heuristic
    mode = "no_input_v1" if not inputs else "default_v1"

    return {
        "id": graph_name,
        "name": graph.get("title") or graph_name.replace("_", " ").title(),
        "badge": "Graph Builder",
        "short_description": short,
        "description": desc,
        "category": "R&D Lab",
        "status": "available",
        "icon_key": "workflow",
        "color": "orange",
        "mode": mode,
        "tags": ["graph-builder", "auto"],
        "features": ["Generated by Graph Builder"],
        "run_visibility": "normal",
        "run_importance": "normal",
        "flow_id": graph_name,
        "github_url": "",
        "input_schema": input_schema or [],
    }


def _infer_input_schema_overrides(
    *,
    inputs: list[Any],
    type_hints: dict[str, str] | None = None,
) -> list[dict[str, Any]]:
    hints = type_hints or {}
    out: list[dict[str, Any]] = []
    for raw in inputs:
        name = str(raw or "").strip()
        if not name:
            continue
        t = str(hints.get(name) or "any").strip().lower()
        widget = "text"
        if t == "number":
            widget = "number"
        elif t == "boolean":
            widget = "switch"
        elif t in {"object", "array"}:
            widget = "json"
        out.append(
            {
                "name": name,
                "type": t,
                "label": name.replace("_", " ").title(),
                "widget": widget,
            }
        )
    return out


def _graph_input_type_hints(
    *,
    context: NodeContext,
    graph_name: str,
    inputs: list[Any],
) -> dict[str, str]:
    reg = context.registry()
    result: dict[str, str] = {}

    # Prefer registry metadata from @graphify registration.
    for ns in ("graph", "graphfn"):
        try:
            meta = reg.get_meta(nspace=ns, name=graph_name, version=None) or {}
        except Exception:
            meta = {}
        io_types = meta.get("io_types") if isinstance(meta, dict) else None
        inp = io_types.get("inputs") if isinstance(io_types, dict) else None
        if isinstance(inp, dict):
            for k, v in inp.items():
                if k:
                    result[str(k)] = str(v)

    # Fallback for graph_fn where io_types may be missing in metadata.
    try:
        gf = reg.get_graphfn(name=graph_name, version=None)
        sig = gf.io_signature() if hasattr(gf, "io_signature") else {}
        for slot in sig.get("inputs", []) or []:
            if isinstance(slot, dict):
                n = str(slot.get("name") or "")
                t = slot.get("type")
            else:
                n = str(getattr(slot, "name", "") or "")
                t = getattr(slot, "type", None)
            if n and t:
                result[n] = str(t)
    except Exception:
        pass

    # Ensure all declared inputs have at least an "any" hint.
    for raw in inputs:
        n = str(raw or "").strip()
        if n and n not in result:
            result[n] = "any"

    return result


async def _propose_app_config_via_llm(
    *,
    context: NodeContext,
    graph_name: str,
    plan: dict[str, Any] | None,
    user_message: str,
) -> dict[str, Any]:
    """
    Ask the LLM to refine an AppConfig-like dict. Falls back to a heuristic config.
    """
    llm = context.llm()
    skills = context.skills()

    graph = (plan or {}).get("graph") or {}
    tools = (plan or {}).get("tools") or []
    inputs = graph.get("inputs") or []
    outputs = graph.get("outputs") or []
    input_type_hints = _graph_input_type_hints(
        context=context, graph_name=graph_name, inputs=inputs
    )
    seed_input_schema = _infer_input_schema_overrides(inputs=inputs, type_hints=input_type_hints)

    system_prompt = skills.compile_prompt(
        GRAPH_BUILDER_SKILL_ID,
        "graph_builder.system",
        "graph_builder.register",
        "graph_builder.style",
        separator="\n\n",
        fallback_keys=["graph_builder.system"],
    )

    seed_config = _fallback_app_config(
        graph_name=graph_name,
        plan=plan,
        input_schema=seed_input_schema,
    )

    user_prompt = (
        "You are helping configure an AetherGraph AppConfig for a graph.\n"
        "You will be given:\n"
        "- The graph name, inputs, outputs.\n"
        "- The high-level plan describing its behavior.\n"
        "- The user's latest request text.\n\n"
        "You MUST return ONLY a JSON object, no markdown, no extra text.\n"
        "The object should be compatible with this shape (keys are optional, "
        "values are examples):\n"
        "{\n"
        '  "id": "random_2d_training_app",\n'
        '  "name": "Random 2D Trainer",\n'
        '  "badge": "Surrogates",\n'
        '  "short_description": "Train and visualize a random 2D regression model.",\n'
        '  "description": "Longer description...",\n'
        '  "category": "R&D Lab",\n'
        '  "status": "available",\n'
        '  "icon_key": "workflow",\n'
        '  "color": "orange",\n'
        '  "mode": "default_v1",\n'
        '  "tags": ["surrogate", "demo"],\n'
        '  "features": ["Differentiable training", "Plots"],\n'
        '  "run_visibility": "normal",\n'
        '  "run_importance": "normal",\n'
        '  "flow_id": "random_2d_training_app",\n'
        '  "github_url": "",\n'
        '  "input_schema": [\n'
        "    {\n"
        '      "name": "top_k",\n'
        '      "type": "number",\n'
        '      "label": "Top K",\n'
        '      "widget": "number",\n'
        '      "placeholder": "20",\n'
        '      "description": "How many items to keep.",\n'
        '      "default": 20\n'
        "    }\n"
        "  ]\n"
        "}\n\n"
        "Rules:\n"
        "- Prefer the given graph_name as a stable id/flow_id.\n"
        "- You may create a nicer human-readable `name` and `badge`.\n"
        "- Use category 'R&D Lab' by default.\n"
        "- Use status 'available'.\n"
        "- If the graph has no required inputs, you MAY use mode 'no_input_v1',\n"
        "  otherwise prefer 'default_v1'.\n\n"
        "- Infer `input_schema` from graph inputs and input types.\n"
        "- Include one `input_schema` item per graph input when possible.\n"
        "- Pick `widget` by type: number->number, boolean->switch, object/array->json, else text.\n"
        "- Keep schema concise and UI-oriented; avoid extra unsupported keys.\n\n"
        "Do NOT include comments. Just a single JSON object.\n\n"
        f"Seed config (you can refine this):\n{json.dumps(seed_config, indent=2, ensure_ascii=False)}\n\n"
        f"Graph summary:\n"
        f"- name: {graph_name}\n"
        f"- inputs: {inputs}\n"
        f"- input_type_hints: {input_type_hints}\n"
        f"- outputs: {outputs}\n"
        f"- tools: {[t.get('name') for t in tools]}\n\n"
        f"Plan JSON:\n{json.dumps(plan or {}, indent=2, ensure_ascii=False)}\n\n"
        f"User's latest message:\n{user_message}\n"
    )

    try:
        resp_text, _usage = await llm.chat(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            max_output_tokens=1024,
        )
        obj = json.loads(resp_text)  # type: ignore[arg-type]
        if not isinstance(obj, dict):
            raise ValueError("LLM did not return a JSON object")
    except Exception:
        context.logger().exception("graph_builder_v2: app config LLM failed; using fallback")
        return seed_config

    # Merge LLM output on top of the seed config, so we always have sane defaults
    merged = dict(seed_config)
    merged.update({k: v for k, v in obj.items() if v is not None})

    # Ensure required core fields are present
    merged.setdefault("id", graph_name)
    merged.setdefault("flow_id", graph_name)
    merged.setdefault("name", graph_name.replace("_", " ").title())
    merged.setdefault("status", "available")
    merged.setdefault("category", "R&D Lab")
    merged.setdefault("mode", "default_v1" if (graph.get("inputs") or []) else "no_input_v1")
    if not isinstance(merged.get("input_schema"), list) or not merged.get("input_schema"):
        merged["input_schema"] = seed_input_schema

    return merged


async def _ensure_graph_registered_from_code(
    *,
    context: NodeContext,
    graph_name: str,
    code_text: str | None,
) -> None:
    """
    Make sure there is a registered graph with `graph_name`.

    - If it's already in the registry, do nothing.
    - Otherwise, exec the generated code in a fresh module so that
      the @graphify decorator runs and registers the graph.
    """
    if not code_text:
        return

    registry = context.registry()

    # Already have the graph? Great, nothing to do.
    try:
        registry.get_graph(name=graph_name, version=None)
        return
    except KeyError:
        pass

    # Build a deterministic-but-unique module name for this code
    h = hashlib.sha256(code_text.encode("utf-8")).hexdigest()[:8]
    module_name = f"_ag_autogen_{graph_name}_{h}"

    if module_name in sys.modules:
        # Already executed once
        return

    module = types.ModuleType(module_name)
    # Give the module a minimal sane __dict__ so imports work
    module.__file__ = f"<autogen:{module_name}>"
    sys.modules[module_name] = module

    # ⚠️ This will execute arbitrary user code; that's an intentional
    # choice in Graph Builder land, but keep security in mind.
    print(
        f"🍎 Graph Builder: executing generated code to register graph '{graph_name}' in module '{module_name}'"
    )
    context.logger().info(
        f"Graph Builder: executing generated code to register graph '{graph_name}' in module '{module_name}'"
    )
    # context.logger().info(f"Generated code for graph '{graph_name}':\n{code_text}")
    try:
        exec(code_text, module.__dict__)
    except Exception as e:
        context.logger().exception("Error executing generated code for graph registration: %s", e)
        raise RuntimeError(f"Failed to execute generated code for graph registration: {e!r}") from e
