"""Streaming scoped blob storage for the local SQLite provider."""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterable, AsyncIterator
from contextlib import suppress
from datetime import UTC, datetime
import hashlib
import json
import os
from pathlib import Path
import sqlite3
from uuid import uuid4

from ...contracts import (
    ArtifactOrphanCleanupResult,
    BlobHead,
    BlobRange,
    BlobWriteResult,
    StorageClock,
    StorageConflictError,
    StorageIntegrityError,
    StorageNotFoundError,
    StorageOpenMode,
    StorageReadOnlyError,
    StorageScope,
    StorageScopeError,
)
from .database import LocalSQLiteDatabase

_BLOB_COMPONENT_VERSION = 2
_CREATE_BLOBS = """
CREATE TABLE local_blobs (
    scope_key TEXT NOT NULL,
    blob_locator TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    hash_algorithm TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    provider_version TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_touched_at TEXT NOT NULL,
    PRIMARY KEY (scope_key, blob_locator)
)
"""
_CREATE_BLOB_HASH_INDEX = """
CREATE INDEX ix_local_blobs_hash ON local_blobs(hash_algorithm, content_hash)
"""
_CREATE_BLOB_ORPHAN_INDEX = """
CREATE INDEX ix_local_blobs_orphan
ON local_blobs(scope_key, last_touched_at, blob_locator)
"""
_CREATE_BLOB_GC_TOMBSTONES = """
CREATE TABLE local_blob_gc_tombstones (
    content_hash TEXT PRIMARY KEY,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    queued_at TEXT NOT NULL
)
"""


class LocalBlobStore:
    """Provider-private immutable blob store with scoped SQLite metadata."""

    def __init__(
        self,
        *,
        database: LocalSQLiteDatabase,
        workspace_root: Path,
        clock: StorageClock,
    ) -> None:
        self._database = database
        self._root = workspace_root.resolve() / "local" / "blobs"
        self._staging = workspace_root.resolve() / "local" / "staging"
        self._mode = database.mode
        self._clock = clock
        self._lock = asyncio.Lock()
        database.install_component(
            name="blobs",
            version=_BLOB_COMPONENT_VERSION,
            statements=(
                _CREATE_BLOBS,
                _CREATE_BLOB_HASH_INDEX,
                _CREATE_BLOB_ORPHAN_INDEX,
                _CREATE_BLOB_GC_TOMBSTONES,
            ),
        )
        if self._mode is StorageOpenMode.READ_WRITE:
            self._root.mkdir(parents=True, exist_ok=True)
            self._staging.mkdir(parents=True, exist_ok=True)

    async def put(
        self,
        scope: StorageScope,
        chunks: AsyncIterable[bytes],
        expected_hash: str | None = None,
        hash_algorithm: str = "sha256",
    ) -> BlobWriteResult:
        """Stage, hash, and atomically publish one scoped immutable blob.

        Chunks are consumed once into provider staging. Content publication and
        scoped metadata establishment share the provider's serialized write window.

        Examples:
            Store generated bytes:
                ```python
                result = await store.put(scope, chunks())
                ```

            Require a known digest:
                ```python
                result = await store.put(scope, chunks(), expected_hash=digest)
                ```

        Args:
            scope: Non-empty canonical owner scope.
            chunks: Asynchronous byte stream consumed exactly once.
            expected_hash: Optional exact lowercase SHA-256 digest.
            hash_algorithm: Exact supported algorithm; currently `sha256`.

        Returns:
            BlobWriteResult: Opaque locator and verified immutable metadata.

        Notes:
            Integrity failure removes staging content and publishes no metadata.
        """
        if self._mode is StorageOpenMode.READ_ONLY:
            raise StorageReadOnlyError("Local blob store is read-only")
        scope_key = _scope_key(scope)
        if hash_algorithm != "sha256":
            raise StorageIntegrityError(f"Unsupported blob hash algorithm: {hash_algorithm!r}")
        temporary = self._staging / f"blob-{uuid4().hex}.tmp"
        digest = hashlib.sha256()
        size = 0
        async with self._lock:
            try:
                handle = await asyncio.to_thread(temporary.open, "xb")
                try:
                    async for chunk in chunks:
                        if not isinstance(chunk, bytes):
                            raise StorageIntegrityError("Blob chunks must be bytes")
                        digest.update(chunk)
                        size += len(chunk)
                        await asyncio.to_thread(handle.write, chunk)
                    await asyncio.to_thread(handle.flush)
                    await asyncio.to_thread(os.fsync, handle.fileno())
                finally:
                    await asyncio.to_thread(handle.close)
                content_hash = digest.hexdigest()
                if expected_hash is not None and content_hash != expected_hash:
                    raise StorageIntegrityError("Blob content hash does not match expected_hash")
                locator = f"blob:sha256:{content_hash}"
                version = f"sha256:{content_hash}"
                target = self._content_path(content_hash)
                target.parent.mkdir(parents=True, exist_ok=True)
                touched_at = self._clock.now()
                _require_utc("clock.now()", touched_at)

                def commit(connection: sqlite3.Connection) -> None:
                    if target.exists():
                        existing_size, existing_hash = _hash_file(target)
                        if existing_size != size or existing_hash != content_hash:
                            raise StorageIntegrityError("Existing blob content is inconsistent")
                        temporary.unlink()
                    else:
                        os.replace(temporary, target)
                    existing = connection.execute(
                        """
                        SELECT content_hash, hash_algorithm, size_bytes, provider_version,
                               last_touched_at
                        FROM local_blobs WHERE scope_key = ? AND blob_locator = ?
                        """,
                        (scope_key, locator),
                    ).fetchone()
                    expected = (content_hash, hash_algorithm, size, version)
                    if existing is not None and tuple(existing[:4]) != expected:
                        raise StorageIntegrityError("Blob locator metadata is inconsistent")
                    if existing is None:
                        connection.execute(
                            """
                            INSERT INTO local_blobs(
                                scope_key, blob_locator, content_hash, hash_algorithm,
                                size_bytes, provider_version, created_at, last_touched_at
                            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                            """,
                            (
                                scope_key,
                                locator,
                                content_hash,
                                hash_algorithm,
                                size,
                                version,
                                touched_at.isoformat(),
                                touched_at.isoformat(),
                            ),
                        )
                    else:
                        previous_touch = datetime.fromisoformat(str(existing[4]))
                        _require_utc("persisted last_touched_at", previous_touch)
                        next_touch = max(previous_touch, touched_at)
                        connection.execute(
                            """
                            UPDATE local_blobs SET last_touched_at = ?
                            WHERE scope_key = ? AND blob_locator = ?
                            """,
                            (next_touch.isoformat(), scope_key, locator),
                        )

                await self._database.transaction(commit)
                return BlobWriteResult(
                    blob_locator=locator,
                    content_hash=content_hash,
                    hash_algorithm=hash_algorithm,
                    size_bytes=size,
                    provider_version=version,
                )
            finally:
                with suppress(OSError):
                    temporary.unlink(missing_ok=True)

    async def read(
        self,
        scope: StorageScope,
        blob_locator: str,
        byte_range: BlobRange | None = None,
    ) -> AsyncIterator[bytes]:
        """Stream complete or ranged content after exact scope validation.

        Metadata is resolved before opening the provider-private content path. The
        store lock keeps retention deletion from racing an active stream.

        Examples:
            Stream complete content:
                ```python
                async for chunk in store.read(scope, locator):
                    consume(chunk)
                ```

            Stream a half-open range:
                ```python
                chunks = store.read(scope, locator, BlobRange(start=0, end=1024))
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque locator returned by `put`.
            byte_range: Optional half-open byte range.

        Returns:
            AsyncIterator[bytes]: Bounded chunks in content order.

        Notes:
            Missing scoped metadata raises `StorageNotFoundError`; paths never escape
            the provider-private blob root.
        """
        async with self._lock:
            row = await self._metadata(scope, blob_locator)
            if row is None:
                raise StorageNotFoundError(blob_locator)
            path = self._content_path(str(row[0]))
            if not path.is_file():
                raise StorageIntegrityError("Blob metadata references missing content")
            start = byte_range.start if byte_range is not None else 0
            remaining = (
                None
                if byte_range is None or byte_range.end is None
                else byte_range.end - byte_range.start
            )
            handle = await asyncio.to_thread(path.open, "rb")
            try:
                await asyncio.to_thread(handle.seek, start)
                while remaining is None or remaining > 0:
                    amount = 64 * 1024 if remaining is None else min(64 * 1024, remaining)
                    chunk = await asyncio.to_thread(handle.read, amount)
                    if not chunk:
                        break
                    if remaining is not None:
                        remaining -= len(chunk)
                    yield chunk
            finally:
                await asyncio.to_thread(handle.close)

    async def head(self, scope: StorageScope, blob_locator: str) -> BlobHead | None:
        """Read scoped immutable blob metadata without content transfer.

        The exact scope and locator are matched in SQLite; physical paths remain
        provider-private.

        Examples:
            Inspect existing content:
                ```python
                head = await store.head(scope, locator)
                ```

            Detect an absent scoped blob:
                ```python
                assert await store.head(scope, missing) is None
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque blob locator.

        Returns:
            BlobHead | None: Immutable metadata or `None` in that exact scope.

        Notes:
            Content-addressed deduplication never grants access across scopes.
        """
        row = await self._metadata(scope, blob_locator)
        if row is None:
            return None
        return BlobHead(
            blob_locator=blob_locator,
            content_hash=str(row[0]),
            hash_algorithm=str(row[1]),
            size_bytes=int(row[2]),
            provider_version=str(row[3]),
        )

    async def delete(
        self,
        scope: StorageScope,
        blob_locator: str,
        provider_version: str | None = None,
    ) -> bool:
        """Delete scoped metadata and unreferenced immutable content.

        Metadata removal commits transactionally. Physical content is removed only
        after the final scope reference disappears.

        Examples:
            Delete an exact version:
                ```python
                deleted = await store.delete(scope, locator, provider_version=version)
                ```

            Treat an absent blob idempotently:
                ```python
                assert await store.delete(scope, missing) is False
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque locator selected by retention.
            provider_version: Optional exact immutable provider version.

        Returns:
            bool: `True` when scoped metadata existed and was deleted.

        Notes:
            A version mismatch raises `StorageConflictError`; read-only mode fails
            before changing metadata or content. An exact owner-scoped artifact
            reference also raises `StorageConflictError` in the delete transaction.
        """
        if self._mode is StorageOpenMode.READ_ONLY:
            raise StorageReadOnlyError("Local blob store is read-only")
        scope_key = _scope_key(scope)
        maintenance_at = self._clock.now()
        _require_utc("clock.now()", maintenance_at)
        async with self._lock:

            def remove(connection: sqlite3.Connection) -> tuple[bool, str | None]:
                row = connection.execute(
                    """
                    SELECT content_hash, provider_version, size_bytes FROM local_blobs
                    WHERE scope_key = ? AND blob_locator = ?
                    """,
                    (scope_key, blob_locator),
                ).fetchone()
                if row is None:
                    return False, None
                if provider_version is not None and row[1] != provider_version:
                    raise StorageConflictError("Blob provider version changed")
                referenced = connection.execute(
                    """
                    SELECT 1 FROM local_artifacts
                    WHERE owner_scope_identity = ?
                      AND (blob_locator = ? OR preview_locator = ?) LIMIT 1
                    """,
                    (scope_key, blob_locator, blob_locator),
                ).fetchone()
                if referenced is not None:
                    raise StorageConflictError("Blob is referenced by an artifact")
                connection.execute(
                    "DELETE FROM local_blobs WHERE scope_key = ? AND blob_locator = ?",
                    (scope_key, blob_locator),
                )
                references = connection.execute(
                    "SELECT COUNT(*) FROM local_blobs WHERE content_hash = ?",
                    (row[0],),
                ).fetchone()[0]
                unreferenced_hash = str(row[0]) if references == 0 else None
                if unreferenced_hash is not None:
                    connection.execute(
                        """
                        INSERT INTO local_blob_gc_tombstones(
                            content_hash, size_bytes, queued_at
                        ) VALUES (?, ?, ?)
                        ON CONFLICT(content_hash) DO NOTHING
                        """,
                        (unreferenced_hash, int(row[2]), maintenance_at.isoformat()),
                    )
                return True, unreferenced_hash

            deleted, unreferenced_hash = await self._database.transaction(remove)
            if unreferenced_hash is not None:
                await self._drain_gc_tombstones(1, content_hash=unreferenced_hash)
            return deleted

    async def reconcile_artifact_orphans(
        self,
        scope: StorageScope,
        *,
        older_than: datetime,
        limit: int = 100,
    ) -> ArtifactOrphanCleanupResult:
        """Delete a bounded reference-safe page of expired artifact blob orphans.

        Candidate selection and deletion share one immediate SQLite transaction with
        an exact artifact-reference recheck. Durable physical-delete tombstones make
        filesystem cleanup retryable after interruption.

        Examples:
            Clean one owner scope:
                ```python
                result = await store.reconcile_artifact_orphans(
                    owner_scope,
                    older_than=cutoff,
                )
                ```

            Drain small maintenance batches:
                ```python
                result = await store.reconcile_artifact_orphans(
                    owner_scope,
                    older_than=cutoff,
                    limit=25,
                )
                ```

        Args:
            scope: Exact canonical artifact-content owner scope.
            older_than: Exclusive timezone-aware UTC last-touch cutoff.
            limit: Positive maximum eligible scoped blobs examined, at most 500.

        Returns:
            ArtifactOrphanCleanupResult: Scoped and physical deletion counts, freed
            bytes, and whether another bounded maintenance call has eligible work.

        Notes:
            Read-only mode fails before mutation. Artifact references and cross-scope
            physical deduplication are rechecked without App/client metadata.
        """
        if self._mode is StorageOpenMode.READ_ONLY:
            raise StorageReadOnlyError("Local blob store is read-only")
        _require_utc("older_than", older_than)
        if isinstance(limit, bool) or not isinstance(limit, int) or not 1 <= limit <= 500:
            raise ValueError("limit must be between 1 and 500")
        scope_key = _scope_key(scope)
        maintenance_at = self._clock.now()
        _require_utc("clock.now()", maintenance_at)
        async with self._lock:

            def remove(connection: sqlite3.Connection) -> tuple[int, bool]:
                rows = connection.execute(
                    """
                    SELECT b.blob_locator, b.content_hash, b.size_bytes
                    FROM local_blobs b
                    WHERE b.scope_key = ? AND b.last_touched_at < ?
                      AND NOT EXISTS (
                          SELECT 1 FROM local_artifacts a
                          WHERE a.owner_scope_identity = b.scope_key
                            AND (
                                a.blob_locator = b.blob_locator
                                OR a.preview_locator = b.blob_locator
                            )
                      )
                    ORDER BY b.last_touched_at, b.blob_locator
                    LIMIT ?
                    """,
                    (scope_key, older_than.isoformat(), limit + 1),
                ).fetchall()
                selected = rows[:limit]
                deleted = 0
                for row in selected:
                    cursor = connection.execute(
                        """
                        DELETE FROM local_blobs
                        WHERE scope_key = ? AND blob_locator = ? AND last_touched_at < ?
                          AND NOT EXISTS (
                              SELECT 1 FROM local_artifacts
                              WHERE owner_scope_identity = ?
                                AND (blob_locator = ? OR preview_locator = ?)
                          )
                        """,
                        (
                            scope_key,
                            row["blob_locator"],
                            older_than.isoformat(),
                            scope_key,
                            row["blob_locator"],
                            row["blob_locator"],
                        ),
                    )
                    if cursor.rowcount != 1:
                        continue
                    deleted += 1
                    remaining = connection.execute(
                        "SELECT 1 FROM local_blobs WHERE content_hash = ? LIMIT 1",
                        (row["content_hash"],),
                    ).fetchone()
                    if remaining is None:
                        connection.execute(
                            """
                            INSERT INTO local_blob_gc_tombstones(
                                content_hash, size_bytes, queued_at
                            ) VALUES (?, ?, ?)
                            ON CONFLICT(content_hash) DO NOTHING
                            """,
                            (
                                row["content_hash"],
                                row["size_bytes"],
                                maintenance_at.isoformat(),
                            ),
                        )
                return deleted, len(rows) > limit

            deleted_scoped, candidate_more = await self._database.transaction(remove)
            deleted_physical, freed_bytes = await self._drain_gc_tombstones(limit)
            tombstones = await self._database.fetch_all(
                "SELECT 1 FROM local_blob_gc_tombstones LIMIT 1"
            )
            return ArtifactOrphanCleanupResult(
                examined=deleted_scoped,
                deleted_scoped_blobs=deleted_scoped,
                deleted_physical_blobs=deleted_physical,
                freed_bytes=freed_bytes,
                has_more=candidate_more or bool(tombstones),
            )

    async def _drain_gc_tombstones(
        self,
        limit: int,
        *,
        content_hash: str | None = None,
    ) -> tuple[int, int]:
        def drain(connection: sqlite3.Connection) -> tuple[int, int]:
            if content_hash is None:
                rows = connection.execute(
                    """
                    SELECT content_hash, size_bytes FROM local_blob_gc_tombstones
                    ORDER BY queued_at, content_hash LIMIT ?
                    """,
                    (limit,),
                ).fetchall()
            else:
                rows = connection.execute(
                    """
                    SELECT content_hash, size_bytes FROM local_blob_gc_tombstones
                    WHERE content_hash = ? LIMIT ?
                    """,
                    (content_hash, limit),
                ).fetchall()
            deleted_physical = 0
            freed_bytes = 0
            for row in rows:
                still_referenced = connection.execute(
                    "SELECT 1 FROM local_blobs WHERE content_hash = ? LIMIT 1",
                    (row["content_hash"],),
                ).fetchone()
                if still_referenced is None:
                    path = self._content_path(str(row["content_hash"]))
                    existed = path.is_file()
                    try:
                        path.unlink(missing_ok=True)
                    except OSError as exc:
                        raise StorageIntegrityError(
                            "Failed to delete orphaned blob content"
                        ) from exc
                    if existed:
                        deleted_physical += 1
                        freed_bytes += int(row["size_bytes"])
                connection.execute(
                    "DELETE FROM local_blob_gc_tombstones WHERE content_hash = ?",
                    (row["content_hash"],),
                )
            return deleted_physical, freed_bytes

        return await self._database.transaction(drain)

    async def _metadata(
        self,
        scope: StorageScope,
        blob_locator: str,
    ) -> sqlite3.Row | None:
        rows = await self._database.fetch_all(
            """
            SELECT content_hash, hash_algorithm, size_bytes, provider_version
            FROM local_blobs WHERE scope_key = ? AND blob_locator = ?
            """,
            (_scope_key(scope), blob_locator),
        )
        return rows[0] if rows else None

    def _content_path(self, content_hash: str) -> Path:
        if len(content_hash) != 64 or any(
            character not in "0123456789abcdef" for character in content_hash
        ):
            raise StorageIntegrityError("Blob content hash is malformed")
        return self._root / "sha256" / content_hash[:2] / content_hash


def _scope_key(scope: StorageScope) -> str:
    populated = scope.as_filter()
    if not populated:
        raise StorageScopeError("Blob operations require a non-empty canonical scope")
    return json.dumps(populated, sort_keys=True, separators=(",", ":"))


def _hash_file(path: Path) -> tuple[int, str]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while chunk := handle.read(64 * 1024):
            size += len(chunk)
            digest.update(chunk)
    return size, digest.hexdigest()


def _require_utc(name: str, value: datetime) -> None:
    if (
        not isinstance(value, datetime)
        or value.tzinfo is None
        or value.utcoffset() != UTC.utcoffset(value)
    ):
        raise ValueError(f"{name} must be a timezone-aware UTC datetime")
