"""Streaming scoped blob storage for the local SQLite provider."""

from __future__ import annotations

import asyncio
from collections.abc import AsyncIterable, AsyncIterator
from contextlib import suppress
import hashlib
import json
import os
from pathlib import Path
import sqlite3
from uuid import uuid4

from ...contracts import (
    BlobHead,
    BlobRange,
    BlobWriteResult,
    StorageConflictError,
    StorageIntegrityError,
    StorageNotFoundError,
    StorageOpenMode,
    StorageReadOnlyError,
    StorageScope,
    StorageScopeError,
)
from .database import LocalSQLiteDatabase

_BLOB_COMPONENT_VERSION = 1
_CREATE_BLOBS = """
CREATE TABLE local_blobs (
    scope_key TEXT NOT NULL,
    blob_locator TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    hash_algorithm TEXT NOT NULL,
    size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
    provider_version TEXT NOT NULL,
    PRIMARY KEY (scope_key, blob_locator)
)
"""
_CREATE_BLOB_HASH_INDEX = """
CREATE INDEX ix_local_blobs_hash ON local_blobs(hash_algorithm, content_hash)
"""


class LocalBlobStore:
    """Provider-private immutable blob store with scoped SQLite metadata."""

    def __init__(
        self,
        *,
        database: LocalSQLiteDatabase,
        workspace_root: Path,
    ) -> None:
        self._database = database
        self._root = workspace_root.resolve() / "local" / "blobs"
        self._staging = workspace_root.resolve() / "local" / "staging"
        self._mode = database.mode
        self._lock = asyncio.Lock()
        database.install_component(
            name="blobs",
            version=_BLOB_COMPONENT_VERSION,
            statements=(_CREATE_BLOBS, _CREATE_BLOB_HASH_INDEX),
        )
        if self._mode is StorageOpenMode.READ_WRITE:
            self._root.mkdir(parents=True, exist_ok=True)
            self._staging.mkdir(parents=True, exist_ok=True)

    async def put(
        self,
        scope: StorageScope,
        chunks: AsyncIterable[bytes],
        expected_hash: str | None = None,
        hash_algorithm: str = "sha256",
    ) -> BlobWriteResult:
        """Stage, hash, and atomically publish one scoped immutable blob.

        Chunks are consumed once into provider staging. Verified content is moved to
        its content-addressed path before scoped metadata commits transactionally.

        Examples:
            Store generated bytes:
                ```python
                result = await store.put(scope, chunks())
                ```

            Require a known digest:
                ```python
                result = await store.put(scope, chunks(), expected_hash=digest)
                ```

        Args:
            scope: Non-empty canonical owner scope.
            chunks: Asynchronous byte stream consumed exactly once.
            expected_hash: Optional exact lowercase SHA-256 digest.
            hash_algorithm: Exact supported algorithm; currently `sha256`.

        Returns:
            BlobWriteResult: Opaque locator and verified immutable metadata.

        Notes:
            Integrity failure removes staging content and publishes no metadata.
        """
        if self._mode is StorageOpenMode.READ_ONLY:
            raise StorageReadOnlyError("Local blob store is read-only")
        scope_key = _scope_key(scope)
        if hash_algorithm != "sha256":
            raise StorageIntegrityError(f"Unsupported blob hash algorithm: {hash_algorithm!r}")
        temporary = self._staging / f"blob-{uuid4().hex}.tmp"
        digest = hashlib.sha256()
        size = 0
        async with self._lock:
            try:
                handle = await asyncio.to_thread(temporary.open, "xb")
                try:
                    async for chunk in chunks:
                        if not isinstance(chunk, bytes):
                            raise StorageIntegrityError("Blob chunks must be bytes")
                        digest.update(chunk)
                        size += len(chunk)
                        await asyncio.to_thread(handle.write, chunk)
                    await asyncio.to_thread(handle.flush)
                    await asyncio.to_thread(os.fsync, handle.fileno())
                finally:
                    await asyncio.to_thread(handle.close)
                content_hash = digest.hexdigest()
                if expected_hash is not None and content_hash != expected_hash:
                    raise StorageIntegrityError("Blob content hash does not match expected_hash")
                locator = f"blob:sha256:{content_hash}"
                version = f"sha256:{content_hash}"
                target = self._content_path(content_hash)
                target.parent.mkdir(parents=True, exist_ok=True)
                if target.exists():
                    existing_size, existing_hash = await asyncio.to_thread(
                        _hash_file,
                        target,
                    )
                    if existing_size != size or existing_hash != content_hash:
                        raise StorageIntegrityError("Existing blob content is inconsistent")
                    temporary.unlink()
                else:
                    os.replace(temporary, target)

                def commit(connection: sqlite3.Connection) -> None:
                    existing = connection.execute(
                        """
                        SELECT content_hash, hash_algorithm, size_bytes, provider_version
                        FROM local_blobs WHERE scope_key = ? AND blob_locator = ?
                        """,
                        (scope_key, locator),
                    ).fetchone()
                    expected = (content_hash, hash_algorithm, size, version)
                    if existing is not None and tuple(existing) != expected:
                        raise StorageIntegrityError("Blob locator metadata is inconsistent")
                    if existing is None:
                        connection.execute(
                            """
                            INSERT INTO local_blobs(
                                scope_key, blob_locator, content_hash, hash_algorithm,
                                size_bytes, provider_version
                            ) VALUES (?, ?, ?, ?, ?, ?)
                            """,
                            (scope_key, locator, content_hash, hash_algorithm, size, version),
                        )

                await self._database.transaction(commit)
                return BlobWriteResult(
                    blob_locator=locator,
                    content_hash=content_hash,
                    hash_algorithm=hash_algorithm,
                    size_bytes=size,
                    provider_version=version,
                )
            finally:
                with suppress(OSError):
                    temporary.unlink(missing_ok=True)

    async def read(
        self,
        scope: StorageScope,
        blob_locator: str,
        byte_range: BlobRange | None = None,
    ) -> AsyncIterator[bytes]:
        """Stream complete or ranged content after exact scope validation.

        Metadata is resolved before opening the provider-private content path. The
        store lock keeps retention deletion from racing an active stream.

        Examples:
            Stream complete content:
                ```python
                async for chunk in store.read(scope, locator):
                    consume(chunk)
                ```

            Stream a half-open range:
                ```python
                chunks = store.read(scope, locator, BlobRange(start=0, end=1024))
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque locator returned by `put`.
            byte_range: Optional half-open byte range.

        Returns:
            AsyncIterator[bytes]: Bounded chunks in content order.

        Notes:
            Missing scoped metadata raises `StorageNotFoundError`; paths never escape
            the provider-private blob root.
        """
        async with self._lock:
            row = await self._metadata(scope, blob_locator)
            if row is None:
                raise StorageNotFoundError(blob_locator)
            path = self._content_path(str(row[0]))
            if not path.is_file():
                raise StorageIntegrityError("Blob metadata references missing content")
            start = byte_range.start if byte_range is not None else 0
            remaining = (
                None
                if byte_range is None or byte_range.end is None
                else byte_range.end - byte_range.start
            )
            handle = await asyncio.to_thread(path.open, "rb")
            try:
                await asyncio.to_thread(handle.seek, start)
                while remaining is None or remaining > 0:
                    amount = 64 * 1024 if remaining is None else min(64 * 1024, remaining)
                    chunk = await asyncio.to_thread(handle.read, amount)
                    if not chunk:
                        break
                    if remaining is not None:
                        remaining -= len(chunk)
                    yield chunk
            finally:
                await asyncio.to_thread(handle.close)

    async def head(self, scope: StorageScope, blob_locator: str) -> BlobHead | None:
        """Read scoped immutable blob metadata without content transfer.

        The exact scope and locator are matched in SQLite; physical paths remain
        provider-private.

        Examples:
            Inspect existing content:
                ```python
                head = await store.head(scope, locator)
                ```

            Detect an absent scoped blob:
                ```python
                assert await store.head(scope, missing) is None
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque blob locator.

        Returns:
            BlobHead | None: Immutable metadata or `None` in that exact scope.

        Notes:
            Content-addressed deduplication never grants access across scopes.
        """
        row = await self._metadata(scope, blob_locator)
        if row is None:
            return None
        return BlobHead(
            blob_locator=blob_locator,
            content_hash=str(row[0]),
            hash_algorithm=str(row[1]),
            size_bytes=int(row[2]),
            provider_version=str(row[3]),
        )

    async def delete(
        self,
        scope: StorageScope,
        blob_locator: str,
        provider_version: str | None = None,
    ) -> bool:
        """Delete scoped metadata and unreferenced immutable content.

        Metadata removal commits transactionally. Physical content is removed only
        after the final scope reference disappears.

        Examples:
            Delete an exact version:
                ```python
                deleted = await store.delete(scope, locator, provider_version=version)
                ```

            Treat an absent blob idempotently:
                ```python
                assert await store.delete(scope, missing) is False
                ```

        Args:
            scope: Non-empty canonical owner scope.
            blob_locator: Exact opaque locator selected by retention.
            provider_version: Optional exact immutable provider version.

        Returns:
            bool: `True` when scoped metadata existed and was deleted.

        Notes:
            A version mismatch raises `StorageConflictError`; read-only mode fails
            before changing metadata or content. An exact owner-scoped artifact
            reference also raises `StorageConflictError` in the delete transaction.
        """
        if self._mode is StorageOpenMode.READ_ONLY:
            raise StorageReadOnlyError("Local blob store is read-only")
        scope_key = _scope_key(scope)
        async with self._lock:

            def remove(connection: sqlite3.Connection) -> tuple[bool, str | None]:
                row = connection.execute(
                    """
                    SELECT content_hash, provider_version FROM local_blobs
                    WHERE scope_key = ? AND blob_locator = ?
                    """,
                    (scope_key, blob_locator),
                ).fetchone()
                if row is None:
                    return False, None
                if provider_version is not None and row[1] != provider_version:
                    raise StorageConflictError("Blob provider version changed")
                referenced = connection.execute(
                    """
                    SELECT 1 FROM local_artifacts
                    WHERE owner_scope_identity = ? AND blob_locator = ? LIMIT 1
                    """,
                    (scope_key, blob_locator),
                ).fetchone()
                if referenced is not None:
                    raise StorageConflictError("Blob is referenced by an artifact")
                connection.execute(
                    "DELETE FROM local_blobs WHERE scope_key = ? AND blob_locator = ?",
                    (scope_key, blob_locator),
                )
                references = connection.execute(
                    "SELECT COUNT(*) FROM local_blobs WHERE content_hash = ?",
                    (row[0],),
                ).fetchone()[0]
                return True, str(row[0]) if references == 0 else None

            deleted, unreferenced_hash = await self._database.transaction(remove)
            if unreferenced_hash is not None:
                with suppress(FileNotFoundError):
                    await asyncio.to_thread(self._content_path(unreferenced_hash).unlink)
            return deleted

    async def _metadata(
        self,
        scope: StorageScope,
        blob_locator: str,
    ) -> sqlite3.Row | None:
        rows = await self._database.fetch_all(
            """
            SELECT content_hash, hash_algorithm, size_bytes, provider_version
            FROM local_blobs WHERE scope_key = ? AND blob_locator = ?
            """,
            (_scope_key(scope), blob_locator),
        )
        return rows[0] if rows else None

    def _content_path(self, content_hash: str) -> Path:
        if len(content_hash) != 64 or any(
            character not in "0123456789abcdef" for character in content_hash
        ):
            raise StorageIntegrityError("Blob content hash is malformed")
        return self._root / "sha256" / content_hash[:2] / content_hash


def _scope_key(scope: StorageScope) -> str:
    populated = scope.as_filter()
    if not populated:
        raise StorageScopeError("Blob operations require a non-empty canonical scope")
    return json.dumps(populated, sort_keys=True, separators=(",", ":"))


def _hash_file(path: Path) -> tuple[int, str]:
    digest = hashlib.sha256()
    size = 0
    with path.open("rb") as handle:
        while chunk := handle.read(64 * 1024):
            size += len(chunk)
            digest.update(chunk)
    return size, digest.hexdigest()
