from __future__ import annotations
from typing import Protocol, Optional, Dict, Any

class AsyncContinuationStore(Protocol):
    async def mint_token(self, run_id: str, node_id: str, attempts: int) -> str: ...
    async def save(self, cont: "Continuation") -> None: ...
    async def get(self, run_id: str, node_id: str) -> Optional["Continuation"]: ...
    async def delete(self, run_id: str, node_id: str) -> None: ...

    async def get_by_token(self, token: str) -> Optional["Continuation"]: ...
    async def mark_closed(self, token: str) -> None: ...
    async def verify_token(self, run_id: str, node_id: str, token: str) -> bool: ...

    async def bind_correlator(self, *, token: str, corr: "Correlator") -> None: ...
    async def find_by_correlator(self, *, corr: "Correlator") -> Optional["Continuation"]: ...

    # Optional helpers
    async def last_open(self, *, channel: str, kind: str) -> Optional["Continuation"]: ...
    async def list_waits(self) -> list[Dict[str, Any]]: ...
    async def clear(self) -> None: ...
    async def alias_for(self, token: str) -> Optional[str]: ...
