from __future__ import annotations
from typing import Protocol, Any, Optional, Iterable, Dict

class AsyncKV(Protocol):
    async def get(self, key: str, default: Any = None) -> Any: ...
    async def set(self, key: str, value: Any, *, ttl_s: Optional[int] = None) -> None: ...
    async def delete(self, key: str) -> None: ...

    # list helpers (JSON list values)
    async def list_append_unique(self, key: str, items: list, *, id_key: str = "id",
                                 ttl_s: Optional[int] = None) -> list: ...
    async def list_pop_all(self, key: str) -> list: ...

    # optional but useful
    async def mget(self, keys: Iterable[str]) -> Dict[str, Any]: ...
    async def mset(self, items: Dict[str, Any], *, ttl_s: Optional[int] = None) -> None: ...
    async def incr(self, key: str, amount: int = 1, *, ttl_s: Optional[int] = None) -> int: ...
    async def exists(self, key: str) -> bool: ...
    async def expire(self, key: str, ttl_s: int) -> bool: ...
    async def scan_prefix(self, prefix: str, limit: int = 1000) -> Iterable[str]: ...
